# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2de42f59621fd5e8894b828c17645049324e8f2d9bbf6b4dd7138f990d4caef0359552ec4fca63e6b5cfdfc0bbd7dd9c79265b9a5d54cab4d1b7ef95c6e14e83

test:
  secret_key_base: 6c113ac304a3b43a3f450f111d41a284d2174bc3c15bad2259c17933bbd9d84eb5350e9321662276023ad6cdec93b352c8a695b4d335d897aca536d6f6d8e7e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
