# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f083576162e0ffa01f25b73cc5e561f02ab2786e6c1c62d9712c9976ad5743e41b2762f6967d646a6cd055d62cd98b5478474f5d2fe3ccee97c05fab31f998e

test:
  secret_key_base: 8fd578007fdf629191aea5935f81ec9f1a588967e83a205235f1938b4167c9bc10467ad87f90bc289006cf67d7651c818341d2810caef2621754bbdc6dde8bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
